### ISSUE TITLE
Can't install Pyosim after recent update

### ISSUE THREAD

**Issue by SoniaSong826** [pyomeca/pyomeca#101]
I get this error when I try to install Pyosim library with `!conda install -y --prefix /usr/local -c kzts opensim` and `import pyosim`.
![image](https://user-images.githubusercontent.com/45267448/84737628-a1814380-afeb-11ea-8278-d74411fd9ef2.png)
I haven't experienced this until recent updates. Pyosim hasn't been updated by several months, so I think maybe there are some conflicts between Pyosim and Pyomeca after the recent commits in Pyomeca. 

Could you please help me to fix this? Thank you!

**Comment by romainmartinez** [comment]
Hi @SoniaSong826 and thanks for the head's up!

We recently did a major pyomeca release ([`2020.0.0`](https://github.com/pyomeca/pyomeca/releases/tag/v2020.0.0)) that is indeed no more compatible with our `pyosim` package.

While waiting for us to do the conversion, you can specify the version of `pyomeca` you were using previously, e.g. `conda install pyomeca=2019.8 -c conda-forge`

By the way, for your repo, I advise you to create an 'environment.yml' file to install your dependencies. 

Let's take the example of [this project](https://github.com/SoniaSong826/CAREN_OpenSim_Pipeline). You could create the following file in the root directory of your project :

`environment.yml`:
```yml
name: your-env-name # replace this with your env name (should be base in colab)
channels:
  - conda-forge
  - kzts
  - pyomeca
dependencies:
  - python
  - pyomeca=2019.8
  - pyosim
  - opensim
#  - ezc3d (not needed as pyomeca depends on this library)
  - pip
  - pip:
    - rarfile
    - zipfile37
```

And just run `conda env update` to install all needed dependencies.

That way, it is easier to keep track of all your dependencies and easier for other users to install them.
Cheers!
